-- public.app_user definition
CREATE TABLE app_user (
	id text NOT NULL,
	first_name text NULL,
	last_name text NULL,
	user_name varchar(256) NULL,
	normalized_user_name varchar(256) NULL,
	email varchar(256) NULL,
	normalized_email varchar(256) NULL,
	email_confirmed bool NOT NULL,
	password_hash text NULL,
	security_stamp text NULL,
	concurrency_stamp text NULL,
	phone_number text NULL,
	phone_number_confirmed bool NOT NULL,
	two_factor_enabled bool NOT NULL,
	lockout_end timestamptz NULL,
	lockout_enabled bool NOT NULL,
	access_failed_count int4 NOT NULL,
	CONSTRAINT pk_app_user PRIMARY KEY (id)
);
CREATE INDEX "email_index" ON public.app_user USING btree (normalized_email);
CREATE UNIQUE INDEX "user_name_index" ON public.app_user USING btree (normalized_user_name);

-- public.app_role definition
CREATE TABLE app_role (
	id text NOT NULL,
	"name" varchar(256) NULL,
	normalized_name varchar(256) NULL,
	concurrency_stamp text NULL,
	CONSTRAINT pk_app_role PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "role_name_index" ON public.app_role USING btree (normalized_name);

-- public."app_role_claim" definition
CREATE TABLE "app_role_claim" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_id text NOT NULL,
	claim_type text NULL,
	claim_value text NULL,
	CONSTRAINT "pk_app_role_claim" PRIMARY KEY (id)
);
CREATE INDEX "ix_app_role_claim_role_id" ON public."app_role_claim" USING btree (role_id);
-- public."app_role_claim" foreign keys
ALTER TABLE public."app_role_claim" ADD CONSTRAINT "fk_app_role_claim_aspnetroles_role_id" FOREIGN KEY (role_id) REFERENCES app_role(id) ON DELETE CASCADE;

-- public."app_user_claim" definition
CREATE TABLE "app_user_claim" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id text NOT NULL,
	claim_type text NULL,
	claim_value text NULL,
	CONSTRAINT "pk_app_user_claim" PRIMARY KEY (id)
);
CREATE INDEX "ix_app_user_claim_user_id" ON public."app_user_claim" USING btree (user_id);
-- public."app_user_claim" foreign keys
ALTER TABLE public."app_user_claim" ADD CONSTRAINT "fk_app_user_claim_aspnetusers_user_id" FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

-- public."app_user_login" definition
CREATE TABLE "app_user_login" (
	login_provider text NOT NULL,
	provider_key text NOT NULL,
	provider_display_name text NULL,
	user_id text NOT NULL,
	CONSTRAINT "pk_app_user_login" PRIMARY KEY (login_provider, provider_key)
);
CREATE INDEX "ix_app_user_login_user_id" ON public."app_user_login" USING btree (user_id);
-- public."app_user_login" foreign keys
ALTER TABLE public."app_user_login" ADD CONSTRAINT "fk_app_user_login_aspnetusers_user_id" FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

-- public."app_user_role" definition
CREATE TABLE "app_user_role" (
	user_id text NOT NULL,
	role_id text NOT NULL,
	CONSTRAINT "pk_app_user_role" PRIMARY KEY (user_id, role_id)
);
CREATE INDEX "ix_app_user_role_role_id" ON public."app_user_role" USING btree (role_id);
-- public."app_user_role" foreign keys
ALTER TABLE public."app_user_role" ADD CONSTRAINT "fk_app_user_role_aspnetroles_role_id" FOREIGN KEY (role_id) REFERENCES app_role(id) ON DELETE CASCADE;
ALTER TABLE public."app_user_role" ADD CONSTRAINT "fk_app_user_role_aspnetusers_user_id" FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

-- public."app_user_token" definition
CREATE TABLE "app_user_token" (
	user_id text NOT NULL,
	login_provider text NOT NULL,
	"name" text NOT NULL,
	value text NULL,
	CONSTRAINT "pk_app_user_token" PRIMARY KEY (user_id, login_provider, name)
);
-- public."app_user_token" foreign keys
ALTER TABLE public."app_user_token" ADD CONSTRAINT "fk_app_user_token_aspnetusers_user_id" FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
