<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>Tree store API components.</Description>
		<Copyright>by Daniele Fusi 2026</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageTags>Cadmus</PackageTags>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<!-- SourceLink-related -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>		
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	
	<!-- internal packages: use references for development, packages for deployment -->
	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\TaxoStore.Core\TaxoStore.Core.csproj" />
		<ProjectReference Include="..\TaxoStore.PgSql\TaxoStore.PgSql.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="TaxoStore.Core" />
		<PackageReference Include="TaxoStore.PgSql" />
	</ItemGroup>
</Project>
