<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<!-- Unified version for all packages, e.g.: -->
		<PackageVersion Include="TaxoStore.Api" Version="0.0.1" />
		<PackageVersion Include="TaxoStore.Api.Controllers" Version="0.0.1" />
		<PackageVersion Include="TaxoStore.Core" Version="0.0.1" />
		<PackageVersion Include="TaxoStore.PgSql" Version="0.0.1" />
		<!-- External dependencies for all packages -->
		<PackageVersion Include="Cadmus.Core" Version="10.0.1" />
		<PackageVersion Include="CsvHelper" Version="33.1.0" />
		<PackageVersion Include="Fusi.Text" Version="6.0.0" />
		<PackageVersion Include="Fusi.Tools" Version="8.0.0" />
		<PackageVersion Include="Fusi.Api.Auth.Controllers" Version="6.0.6" />
		<PackageVersion Include="Fusi.Api.Auth.Models" Version="6.0.6" />
		<PackageVersion Include="Fusi.DbManager.PgSql" Version="6.0.1" />
		<PackageVersion Include="MessagingApi" Version="6.0.0" />
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
		<PackageVersion Include="Npgsql" Version="10.0.1" />
		<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageVersion Include="Polly" Version="8.6.5" />
		<PackageVersion Include="Scalar.AspNetCore" Version="2.12.18" />
		<PackageVersion Include="Serilog" Version="4.3.0" />
		<PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
		<PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageVersion Include="coverlet.collector" Version="6.0.4" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageVersion Include="xunit" Version="2.9.3" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
</Project>